function mode = ad9144setup(ads7, modeIn)
%
% *** Do not edit this file.                    ***
% *** Contains evalboard specific configuration ***
%
% This is the setup function for the ad9144.
% The JESD204 lanes and link parameters for
% the dac modes are setup.
%
% ads7   - Ads7 IHardwareDevice
% modeIn - The AD9144 dac mode

mode = modeIn;
disp(['Setting up mode: ', num2str(mode)]);
%disp(ads7.FriendlyName)

% Get the JESD204Interface
jesd204 = ads7.JESD204;

% Single link, first framer
frameNum = 0+1;      % first framer (.net uses 0 based arrays)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lane configuration for AD9144-FMC-EBZ
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
jesd204.Lanes(0+1).InvertPolarity = false;
jesd204.Lanes(1+1).InvertPolarity = false;
jesd204.Lanes(2+1).InvertPolarity = false;
jesd204.Lanes(3+1).InvertPolarity = false;

jesd204.Lanes(4+1).InvertPolarity = true;
jesd204.Lanes(5+1).InvertPolarity = true;
jesd204.Lanes(6+1).InvertPolarity = true;
jesd204.Lanes(7+1).InvertPolarity = true;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% AD9144 DAC Mode JESD204 Paramters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cM = containers.Map('KeyType', 'int32', 'ValueType', 'any');

% Index of param intable
M=1;L=2;S=3;F=4;K=5;HD=6;N=7;Np=8;Scrm=9;Sub=10;

%Mode     M  L  S  F  K  HD      N   Np  Scrm  Sub
cM(0)  = [4  8  1  1  32 true    16  16  true  1  ];
cM(1)  = [4  8  2  2  16 false   16  16  true  1  ];
cM(2)  = [4  4  1  2  16 false   16  16  true  1  ];
cM(3)  = [4  2  1  4  16 false   16  16  true  1  ];
cM(4)  = [2  4  1  1  32 true    16  16  true  1  ];
cM(5)  = [2  4  2  2  16 false   16  16  true  1  ];
cM(6)  = [2  2  1  2  16 false   16  16  true  1  ];
cM(7)  = [2  1  1  4  16 false   16  16  true  1  ];
cM(9)  = [1  2  1  1  32 true    16  16  true  1  ];
cM(10) = [1  1  1  2  16 false   16  16  true  1  ];

modeParams = cM(mode);

jesd204.FramerCount = 1;
jesd204.Framers(frameNum).M = modeParams(M)-1;
jesd204.Framers(frameNum).L = modeParams(L)-1;
jesd204.Framers(frameNum).S = modeParams(S)-1;
jesd204.Framers(frameNum).F = modeParams(F)-1;
jesd204.Framers(frameNum).K = modeParams(K)-1;
jesd204.Framers(frameNum).HD = modeParams(HD)-1;
jesd204.Framers(frameNum).N = modeParams(N)-1;
jesd204.Framers(frameNum).Np = modeParams(Np)-1;
jesd204.Framers(frameNum).Scrambling = modeParams(Scrm);

if (modeParams(Sub)==0)
    jesd204.Framers(frameNum).Subclass = AnalogDevices.DPG.Interfaces.eSubclass.Subclass0;
elseif (modeParams(Sub)==1)
    jesd204.Framers(frameNum).Subclass = AnalogDevices.DPG.Interfaces.eSubclass.Subclass1;
else
    jesd204.Framers(frameNum).Subclass = AnalogDevices.DPG.Interfaces.eSubclass.Subclass2;
end

end